### ISSUE TITLE
pytorch_transformers issue

### ISSUE THREAD

**Issue by yassmine-lam** [aub-mind/arabert#100]
Hi,

I tried to run this code

from pytorch_transformers.modeling_bert import BertModel
bert_base_model = BertModel.from_pretrained("aubmindlab/bert-base-arabertv01")

but it gave me this error

OSError: file aubmindlab/bert-base-arabertv01 not found

Could someone help plz

Thank u

**Comment by WissamAntoun** [comment]
you have to migrate from pytorch_transformers to transformers

Just `pip install transformers` and do  `from transformers import BertModel`

**Comment by yassmine-lam** [comment]
ok thank u
