### ISSUE TITLE
Downoald AraBERT models

### ISSUE THREAD

**Issue by yassmine-lam** [aub-mind/arabert#101]
another question plz

where to download the arabert models instead of using hagging face?
Also I think arabert version 2 doesn t work with transformers version 2 ? any ideas plz

thanks

**Comment by WissamAntoun** [comment]
you can just go to the model page on huggingface and click the down arrow
![image](https://user-images.githubusercontent.com/44616226/116619555-47f6de80-a949-11eb-8e7a-727755a90b14.png)

**Comment by yassmine-lam** [comment]
Hi,

I tried to clone the repo of this model 

git clone https://huggingface.co/aubmindlab/bert-base-arabertv02

but the pytorch_model.bin file is almost empty

any ideas plz

thank u

**Comment by WissamAntoun** [comment]
you need to install `git lfs` which stands for git large file system. 
you can do that as follows:
```bash
pip install cookiecutter
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install
```

**Comment by yassmine-lam** [comment]
ok thanks for ur answer but I coudn t found the tensorflow version with checkpoint files

**Comment by WissamAntoun** [comment]
the tensorflow 1 files are compressed in a file named `tf1_model.tar.gz`, the tensorflow 2 are in the `tf_model.h5` files.
