### ISSUE TITLE
Using AraELECTRA

### ISSUE THREAD

**Issue by alaa-buktaish** [aub-mind/arabert#108]
Hi,
I tried to use the AraELECTRA model from Hugging Face
but it's give me this error message :

Can't load config for 'wissamantoun/araelectra-base-artydiqa'. Make sure that:
- 'wissamantoun/araelectra-base-artydiqa' is a correct model identifier listed on 'https://huggingface.co/models'
- or 'wissamantoun/araelectra-base-artydiqa' is the correct path to a directory containing a config.json file

**Comment by WissamAntoun** [comment]
is the transformers version `4.0.0` and above?

**Comment by alaa-buktaish** [comment]
yes, it's 4.6.0

**Comment by WissamAntoun** [comment]
i tried this and it worked 
```python
from transformers import AutoModelForQuestionAnswering

model = AutoModelForQuestionAnswering.from_pretrained("wissamantoun/araelectra-base-artydiqa")
```

This model is different than `aubmindlab/araelectra-base-discriminator` . `wissamantoun/araelectra-base-artydiqa` is already trained on question answering
