### ISSUE TITLE
Clarification regarding the license 

### ISSUE THREAD

**Issue by ghaddarAbs** [aub-mind/arabert#136]
Hi, 

Thanks for sharing your great work!!!!!

The license get me confused and I was wondering what it the nearest one to it:

- Apache v2.0 (as google-BERT) 
- MIT
- or a  stricter Licence

Thanks,

**Comment by WissamAntoun** [comment]
it is actually very similar to the WordNet license here https://wordnet.princeton.edu/license-and-commercial-use

**Comment by ghaddarAbs** [comment]
I see .... Thanks for the clarifications !!!!
