### ISSUE TITLE
Where can I find or how to generate the "vocab.txt" file to pre-train on a new dataset?

### ISSUE THREAD

**Issue by AhmedHassan127** [aub-mind/arabert#141]
Dears,
I am trying to pre-train the AraELECTRA on a new dataset, Where can I find or how to generate the "vocab.txt" file to pre-train on a new dataset?
Thanks in advance.

**Comment by WissamAntoun** [comment]
Here a good tutorial on training your own tokenizer https://towardsdatascience.com/how-to-build-a-wordpiece-tokenizer-for-bert-f505d97dddbb 

But bare in mind, that continuing to train AraELECTRA on your new dataset might get you better result than training with a new vocabulary from scratch

**Comment by AhmedHassan127** [comment]
Thank you so much. I actually agree with you, that's why I was hoping that you share the "vocab.txt" file that you used for your own training, it will save me so much time.
![image](https://user-images.githubusercontent.com/27693040/145760752-9e922dd4-3632-4b77-89b3-b90d934a9b7b.png)

**Comment by WissamAntoun** [comment]
you can find all the files here https://huggingface.co/aubmindlab/araelectra-base-discriminator/tree/main

**Comment by AhmedHassan127** [comment]
Thank you 3000 <3
