### ISSUE TITLE
tensorflow version of arabert v01

### ISSUE THREAD

**Issue by karimmahalian** [aub-mind/arabert#150]
Hi,

Could you please provide us with the tensorflow files of arabert v01. There are not available at hugging face unlike v02. I need the chkpt, config, and vocab files.

Many thanks in advance.

**Comment by WissamAntoun** [comment]
here you go https://drive.google.com/drive/folders/1xqNwdlaMXabFzCUtmVwQZDPbCib4U6zn?usp=sharing

**Comment by karimmahalian** [comment]
Hi,

First, thank you for sharing the code with us. However, I am facing trouble when running this code using this version of arabert (v01)


model_bert = load_trained_model_from_checkpoint(
    config_path,
    checkpoint_path,
    seq_len=SEQ_LEN,
    output_layer_num=4,
    trainable=True
)

Code keeps running with not stop

However, when using v02 of arabert, code is executed in a few minutes.

Could you help plz? I need to run this code with 01 version 

Many thanks in advance

**Comment by WissamAntoun** [comment]
weird, does it work if you try one of old examples https://github.com/aub-mind/arabert/blob/master/examples/old/araBERT_(Updated_Demo_TF).ipynb
