### ISSUE TITLE
the + symbol is showing up in the tokens, what am i doing wrong?

### ISSUE THREAD

**Issue by AhmedAbuelnour** [aub-mind/arabert#151]
this is my code
![image](https://user-images.githubusercontent.com/7360803/154832424-29ee1375-86bb-49e2-bcbb-d30fdcd80083.png)
![image](https://user-images.githubusercontent.com/7360803/154832433-c2eda4d4-3602-4340-afcf-f8d0c26467fd.png)
![image](https://user-images.githubusercontent.com/7360803/154832439-8167e220-9249-4854-8b74-d6e960c7b815.png)

What's wrong with it? why + symbol is showing up in the tokens?

**Comment by WissamAntoun** [comment]
it seems this is a bug in the transformers library and the fast autotokenizers. I think it is related to this issue https://github.com/huggingface/transformers/issues/12223 

For now the issue can be solved using the BertTokenizer or setting 'use_fast = False'

![image](https://user-images.githubusercontent.com/44616226/155042213-974f33c3-f82b-46bb-9314-4a83706bd41a.png)

**Comment by AhmedAbuelnour** [comment]
Thank you it works :)
