### ISSUE TITLE
AraBERTv0.2-Twitter-large TF

### ISSUE THREAD

**Issue by Mohamed-Aziz-Ben-Nessir** [aub-mind/arabert#159]
Hello! 
where can I find the AraBERTv0.2-Twitter-large/base for TF, please?

**Comment by WissamAntoun** [comment]
Unfortunately, the training for that model was done in pytorch. You will be able to use it directly with TF2, but you need to manually convert it using this script here https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/convert_bert_pytorch_checkpoint_to_original_tf.py

**Comment by Mohamed-Aziz-Ben-Nessir** [comment]
I see, I already loaded it from pt but that didn't end up well. Thank you for your answer tho!
