### ISSUE TITLE
Can I  I extract embeddings for a sentence or a set of words directly from pre-trained Aragbt2 model?

### ISSUE THREAD

**Issue by LatifaA2** [aub-mind/arabert#161]
I want to know if I can extract embedding from the output of last layer of AraGBT2 model for a certain sentence ?

**Comment by LatifaA2** [comment]
So, I can feed these emdeddings to a new seq2seq model?

**Comment by WissamAntoun** [comment]
yes you can, check this notebook to see how https://colab.research.google.com/drive/1Xk8IGcwGTr-YNlB6lhl8jYdIU_M7Mcjx?usp=sharing#scrollTo=lS_OtDJIaAXq

**Comment by LatifaA2** [comment]
Thank you so much for your help. 
just one last thing, I want to build an embedding matrix so I can feed it to a new seq2seq model. My model handle the sentence word by word, so I think that the embedding matrix should contain the embedding for each word alone, but I want to extract the embedding of the word based on the context of sentence. Do you have any idea how I can do this using AraGBT2 ?

**Comment by WissamAntoun** [comment]
If you want to do that the best way is to skip the embedding layer and just replace it with a araGPT2 model with it's weights frozem (requires_grad=False). 

I suggest using arabert or araelectra if you are feeding the embeddings to the encoder.

**Comment by LatifaA2** [comment]
Okay, thank you very much for help!
