### ISSUE TITLE
Can't load weights

### ISSUE THREAD

**Issue by habibagamal** [aub-mind/arabert#19]
Hi, 
I am using tensorflow with transformers. 
That's the code I have so far. 

```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModel

arabert_tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv01",do_lower_case=False)
arabert_model = TFAutoModel.from_pretrained("aubmindlab/bert-base-arabertv01")
```

However, I get this error. 

> OSError: Can't load weights for 'aubmindlab/bert-base-arabertv01'. Make sure that:
> 
> - 'aubmindlab/bert-base-arabertv01' is a correct model identifier listed on 'https://huggingface.co/models'
> 
> - or 'aubmindlab/bert-base-arabertv01' is the correct path to a directory containing a file named one of tf_model.h5, pytorch_model.bin.

I do not have the model files locally, but they are on 'https://huggingface.co/models', but I notice that for the tensorflow version, there's no .h5 file. Is this the problem?

**Comment by WissamAntoun** [comment]
Hey,

yes, the issue was because we didn't have a TensorFlow2 compatible model on https://huggingface.co/models, I just converted the PyTorch checkpoints to TF2 and uploaded them.

Try it now and let me know if it worked for you

**Comment by habibagamal** [comment]
It loaded the weights. Thanks. 
Do you have an example where this model was used in text generation?

**Comment by habibagamal** [comment]
I get this disclaimer
> Some weights of the model checkpoint at aubmindlab/bert-base-arabertv01 were not used when initializing TFBertForMaskedLM:
when I have this code 
```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelWithLMHead, TFBertForMaskedLM 

arabert_tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv01",do_lower_case=False)
arabert_model = TFBertForMaskedLM .from_pretrained("aubmindlab/bert-base-arabertv01")
```
or this code
```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelWithLMHead, TFBertForMaskedLM 

arabert_tokenizer = AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabertv01",do_lower_case=False)
arabert_model = TFAutoModelWithLMHead.from_pretrained("aubmindlab/bert-base-arabertv01")
```
Is this normal?

**Comment by WissamAntoun** [comment]
Although BERT is ideal for language generation, it still can be done. check this article with the github implementation https://prakhartechviz.blogspot.com/2020/04/natural-language-generation-using-bert.html .

Also the warning is normal since the model contains parameters that were used during pre-training and wont be used again like the layers used for next sentence prediction. So it is safe to ignore it

**Comment by WissamAntoun** [comment]
@habibagamal  can I close this issue? or there is something else you want to know?

**Comment by habibagamal** [comment]
Sure, close it. Thanks for your help.
