### ISSUE TITLE
problem with arcd_preprocessing script

### ISSUE THREAD

**Issue by haythemtellili** [aub-mind/arabert#20]
when i run this `!python /content/arcd_preprocessing.py \
    --input_file="/content/arcd-test.json" \
    --output_file="arcd-test-pre.json" \
    --do_farasa_tokenization=True \
    --use_farasapy=True \`

i get this error :
` "do_farasa_tokenization is enabled, please provide the path_to_farasa"
ValueError: do_farasa_tokenization is enabled, please provide the path_to_farasa`

**Comment by WissamAntoun** [comment]
OH! 
try `!python /content/arcd_preprocessing.py \ --input_file="/content/arcd-test.json" \ --output_file="arcd-test-pre.json" \ --do_farasa_tokenization=True \ --use_farasapy=True \ --path_to_farasa="anything"`

When we updated the code to support farasapy we left this line by mistake `    if FLAGS.do_farasa_tokenization and (FLAGS.path_to_farasa == None):
        raise ValueError(
            "do_farasa_tokenization is enabled, please provide the path_to_farasa"
        )`

so just provide any string to the `--path_to_farasa` just to skip this check. Also make sure you have farasapy installed

We will fix the issue soon, probably by tonight

**Comment by haythemtellili** [comment]
Yes thank you, i deleted this part `if FLAGS.do_farasa_tokenization and (FLAGS.path_to_farasa == None): raise ValueError( "do_farasa_tokenization is enabled, please provide the path_to_farasa" )` and it worked.
