### ISSUE TITLE
Do AraBERT support word cut? For example, apples cut to appl/apple

### ISSUE THREAD

**Issue by guotong1988** [aub-mind/arabert#200]
@WissamAntoun Thank you very much!

**Comment by WissamAntoun** [comment]
Well it depends, if you use the V01 and V02 models, they should behave as the normal BERT model with workpiece, as in there is a chance that an Arabic word like `Apples` gets segments into `"Appl"`, and `"##es"`, but it is not guaranteed.

While if you use the V1 and V2 version with pre-segmentation, the arabert preprocessor will first morphological segment a word (ex: `altifahat` (Arabic for `"the apples"` but in Arabic it's concatenated) to `"al+ tifah +at"` which can be roughly seen as `"the+ appl +es"`). Then comes the normal  bert tokenizer and applies workpiece on top of that, so you might endup with the word `"appl"` tokenized again if it is not common.

**Comment by guotong1988** [comment]
Thank you. I mean, support input `apples` for AraBERT and output `appl/apple`

**Comment by WissamAntoun** [comment]
You mean you want to have it predict `appl` if the output token is `Apples`? If yes then the only concern would be that both input and output have to have the same len after tokenization. Let's say if Apples tokenized to one token, apply might tokenized into two tokens like `app ##l`

**Comment by guotong1988** [comment]
Thank you! I mean, predict `appl` if the input word (for AraBERT) is `apples`? like NER/extract for a word to output word-stem.

**Comment by WissamAntoun** [comment]
Yes, but again check if the output word is also a single token
