### ISSUE TITLE
Pytorch demo includes class definition for an imported class

### ISSUE THREAD

**Issue by mikeFore4** [aub-mind/arabert#22]
In the examples/AraBERT_PyTorch_Demo.ipynb notebook, in the "Model Finetuning" section in the "Imports" cell, there is a line reading:
```
from transformers import WEIGHTS_NAME, BertConfig, BertForSequenceClassification, BertTokenizer
```
But in the very next cell, there's a class definition for BertForSequence Classification. This will overwrite the imported class. One of these three things should happen and I'm not sure which because I'm not sure what is intended:
1) Remove the import statement and just use the class definition
2) Remove the class definition and just use the imported class
3) Name the defined class something different and have it inherit from the imported class

Please provide clarity of what is going on here.

**Comment by WissamAntoun** [comment]
yea, it's because i used the model to demo how you can finetune arabert, and wanted to show people how is the classification layer built. The redefined class is a literal copy\paste from the library. 
i should have probably not included the first import

**Comment by mikeFore4** [comment]
Thanks! Makes sense.
