### ISSUE TITLE
Question Answering training data

### ISSUE THREAD

**Issue by Khalid-Nabigh** [aub-mind/arabert#23]
How did you combined the whole Arabic-SQuAD and the training-set of ARCD in one json file (turk_combined_all_pre.json)? would you mind to release it?

**Comment by WissamAntoun** [comment]
Here the code that used.

```python
from SOQAL.data_helpers.data_split import train_test_split, combine_json_files

train_test_split("SOQAL/data/arcd.json",0.5)
combine_json_files(["SOQAL/data/Arabic-SQuAD.json","SOQAL/data/arcd-test.json"])
```
The functions and data are available on `https://github.com/husseinmozannar/SOQAL`.

To preprocess the training and testing set you need to use the [`arcd_preprocessing.py`](https://github.com/aub-mind/arabert/blob/master/arcd_preprocessing.py) as follows: 
(Note: set farasa flag so False if you are using AraBERTv0.1)
```bash
python arcd_preprocessing.py \
    --input_file="/PATH_TO/arcd-test.json" \
    --output_file="arcd-test-pre.json" \
    --do_farasa_tokenization=True \
    --use_farasapy=True

python arcd_preprocessing.py \
    --input_file="/PATH_TO/turk_combined.json" \
    --output_file="turk_combined_all_pre.json" \
    --do_farasa_tokenization=True \
    --use_farasapy=True
```
