### ISSUE TITLE
max seq length effect on the model

### ISSUE THREAD

**Issue by AbdulghaniAhlam** [aub-mind/arabert#25]
Does max_seq_length value affect on the model results?
in my Dataset, for example, the max length for training or testing set can't exceed 64, so can I use 128 as a value for max_seq_length, and what will happen if I use 256 or 512??

**Comment by WissamAntoun** [comment]
It shouldn't matter a lot (I saw some improvements when I tried longer sequences, but Batch Size might get reduced which can hurt performance), but shorter lengths should make the training and inference faster

**Comment by AbdulghaniAhlam** [comment]
OK. thank you
