### ISSUE TITLE
can not find arabert model using transformers

### ISSUE THREAD

**Issue by yaman-hub** [aub-mind/arabert#29]
Although I install transformers, but when I try to import using the following code: 
```
from arabert.preprocess_arabert import never_split_tokens, preprocess
```
it gives me the following error: 
ModuleNotFoundError: No module named 'arabert'
known that I am working with pytorch. 
how I can fix this problem, please.

**Comment by mapmeld** [comment]
I think you want to set up your environment so this repo (arabert) is in the same directory as your script.

```bash
mkdir project
cd project
pip install transformers py4j PyArabic farasapy
git clone https://github.com/aub-mind/arabert
pip install -r arabert/requirements.txt
python your_script.py
```
