### ISSUE TITLE
Colab Demo missing two lines to use TPU.

### ISSUE THREAD

**Issue by Soug-crypto** [aub-mind/arabert#3]
Great work. God knows it is needed. 

I fixed it by adding the following in the TensorFlow Training part:
`from google.colab import auth
auth.authenticate_user()`

**Comment by WissamAntoun** [comment]
Just fixed it, thanks for the pointing the issue and for the feedback 😊

**Comment by haythemtellili** [comment]
I am ruuning the run_squad script on colab, what i have to do here --tpu_name=$TPU_ADDRESS \ ?

**Comment by WissamAntoun** [comment]
if you are using a GPU dont include it.

If you are using a TPU your model should be on a google bucket. Follow this colab tutorial to get more info on how to get the TPUADDRESS https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/bert_finetuning_with_cloud_tpus.ipynb#scrollTo=191zq3ZErihP

**Comment by WissamAntoun** [comment]
@haythemtellili
