### ISSUE TITLE
compute metrics is not executed using Trainer from transformers

### ISSUE THREAD

**Issue by rajae-Bens** [aub-mind/arabert#31]
Hi,

I am trying to execute the code from this notebook 
AraBERT_Text_Classification_with_HF_Trainer_Pytorch_GPU.ipynb

but when training the model, I think the compute_metrics function is not executed because the classification report and confusion metrics are not calculated

here is the output of the training process 
![Screen Shot 2020-11-03 at 9 04 50 AM](https://user-images.githubusercontent.com/58187895/97961816-41314980-1db4-11eb-979e-20708e2a62a6.png)

Could someone help plz 
thank u

**Comment by DonKhaled** [comment]
same issue, waiting for response

**Comment by WissamAntoun** [comment]
I start looking into it, HuggingFace are changing their trainer API constantly

**Comment by WissamAntoun** [comment]
in the meantime try `pip install transformers==2.11.0`

**Comment by rajae-Bens** [comment]
Yes it worked!
Thank s for ur help!!
