### ISSUE TITLE
classification_report using tensorflow estimator

### ISSUE THREAD

**Issue by rajae-Bens** [aub-mind/arabert#36]
Hi, 

I tried to run this notebook araBERT_(Updated_Demo_TF).ipynb and the evaluate function show only eval_accuracy and eval_loss and I need to show the classification report.

I tried to get predictions from the model using this 

predictions = np.array([p['probabilities'] for p in predictions])

but the length of my predictions(=448) is different from my true_labels(=453)

could u help plz 
 
thank u

**Comment by WissamAntoun** [comment]
I recommend you use the `AraBERT_with_fast_bert.ipynb` or 1AraBERT_Text_Classification_with_HF_Trainer_Pytorch_GPU.ipynb` those are much easier to work with, and the later already print the classification report during training

**Comment by rajae-Bens** [comment]
Ok I will try them 

thank u
