### ISSUE TITLE
Tensorflow models in .pb format.

### ISSUE THREAD

**Issue by Soug-crypto** [aub-mind/arabert#4]
I am having a hard time transforming the models in .pb format. I want to you use it with a node library that requires it to be in .pb format. I tried to do it with ONNX but with no luck. Any chance you can upload the .bp and/or .pth  for the models? 
Thanks in advance.

**Comment by fadybaly** [comment]
hey @Soug-crypto, have you tried converting the checkpoint using tensorflow estimator export? I haven't attempted this using ONNX before, but in all cases can you share the error you're getting? maybe we can help.
