### ISSUE TITLE
Regard bert-base-arabertv2

### ISSUE THREAD

**Issue by Phd-Student2018** [aub-mind/arabert#43]
"

**Comment by Phd-Student2018** [comment]
After I change the transformers in to 4.1.1, I get another error in tokenizer 
after that i change into  "!pip install transformers==4.0.0rc1" the problem is solved but another error ocuures into traning 
function 
The error is :
TypeError                                 Traceback (most recent call last)
<ipython-input-34-0f47a8e7624f> in <module>()
      2 best_f1 = 0
      3 for epoch in range(EPOCHS):
----> 4     train_loss = train_fn(train_dataloader, model, optimizer, device, scheduler)
      5     eval_metrics, eval_loss = eval_fn(test_dataloader, model, device)
      6     print(f"Train Loss = {train_loss} Valid Loss = {eval_loss}")

5 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    981     return (_VF.dropout_(input, p, training)
    982             if inplace
--> 983             else _VF.dropout(input, p, training))
    984 
    985 

TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

**Comment by WissamAntoun** [comment]
I just updated the NER example colab with support for the new AraBERT

here is the link: https://colab.research.google.com/drive/1M1yH8rqbxowlSd5R-jr8eBVfGbIyp1zC?usp=sharing 

For AraBERTv2 you need to use the custom model script that I included in the colab and not the Trainer, since I can't do pre-segmentation inside the huggingface dataset class

**Comment by Phd-Student2018** [comment]
> I just updated the NER example colab with support for the new AraBERT
> 
> here is the link: https://colab.research.google.com/drive/1M1yH8rqbxowlSd5R-jr8eBVfGbIyp1zC?usp=sharing
> 
> For AraBERTv2 you need to use the custom model script that I included in the colab and not the Trainer, since I can't do pre-segmentation inside the huggingface dataset class

Thank you

**Comment by WissamAntoun** [comment]
For AraBERT v0.1 or AraBERT v0.2 you can use either parts,

but for AraBERT v1 or AraBERT v2 you need to use the second part with custom training script

**Comment by Phd-Student2018** [comment]
Thanks alot.
the code worked fine yesterday but today it doesnt work , I get this error
BrokenPipeError                           Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/farasa/__base.py in _run_task_interactive(self, btext)
    203             self.__task_proc.stdin.write(btext)
--> 204             self.__task_proc.stdin.flush()
    205         except BrokenPipeError as broken_pipe:

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

BrokenPipeError                           Traceback (most recent call last)
8 frames
/usr/local/lib/python3.6/dist-packages/farasa/__base.py in _run_task_interactive(self, btext)
    210             self.__task_proc.stdin.flush()
    211             self.__task_proc.stdin.write(btext)
--> 212             self.__task_proc.stdin.flush()
    213 
    214         output = self.__task_proc.stdout.readline().decode("utf8").strip()

BrokenPipeError: [Errno 32] Broken pipe

**Comment by WissamAntoun** [comment]
It seems that the error is from the farasapy package, I think the download link for the farasa packages is down 

https://farasa-api.qcri.org/farasapy/releases/download/toolkit-bins-released/farasa_bin.zip 

We'll have to wait for QCRI to figure it out

**Comment by WissamAntoun** [comment]
It's working now

**Comment by Phd-Student2018** [comment]
Thank you very much

**Comment by sahar1020** [comment]
We have a graduation project whose mission is to create extractive summaries of Arab research papers, and we want to use your AraBERT model. How can we do this, and should we perform a fine tuning process on it, knowing that we have a database of 500 papers with a summary for each research paper?
