### ISSUE TITLE
How to split dataset (HARD,ArsenTD-Lev,LABR,ANERCorp) ?

### ISSUE THREAD

**Issue by HIT16S** [aub-mind/arabert#5]
I'm spliting datasets(HARD,ArsenTD-Lev,LABR,ANERCorp) follow your way, but some of the datasets are not splited by the authors. In your paper(AraBERT: Transformer-based Model for Arabic Language Understanding), "We use the splits provided by the dataset 's authors, when available. And the standard of 80% and 20% when not2)" and "the scripts, informs the to create the datasets are available on our lot repo https://github.com/aub-mind/arabert " , but I didn't find it in your repo. Can you upload this part of the script? Thank you very much!

**Comment by WissamAntoun** [comment]
I just added the script that we used e1cc727fd2a3fc4e6ab98eb35c7c8fa56e28982e

It should work fine if you have the same files.
Let me know if you face issues

**Comment by HIT16S** [comment]
@WissamAntoun  thank you very much! I will have a try.

**Comment by HIT16S** [comment]
@WissamAntoun  Can you share your scripts for ANERCorp？
