### ISSUE TITLE
error   'tensorflow' has no attribute 'gfile'

### ISSUE THREAD

**Issue by younesKha** [aub-mind/arabert#6]
error appears when run this script 
bert_tokenizer = tokenization.FullTokenizer(ARABERT_PATH+"/vocab.txt")

/content/arabert/tokenization.py in load_vocab(vocab_file)
    123   index = 0
    124   print(tf.__version__)
--> 125   with tf.gfile.GFile(vocab_file, "r") as reader:
    126     while True:
    127       token = convert_to_unicode(reader.readline())
AttributeError: module 'tensorflow' has no attribute 'gfile'

**Comment by WissamAntoun** [comment]
The code was written with TensorFlow 1.x, if you are running it on colab, restart the runtime and run this ```%tensorflow_version 1.x``` and don't try to pip install tensorflow 1.x as per google's recommendation https://colab.research.google.com/notebooks/tensorflow_version.ipynb#scrollTo=NeWVBhf1VxlH

**Comment by younesKha** [comment]
hi  thx for answering your solution is working

**Comment by younesKha** [comment]
Hi I am a master student and working in a paper  to compare the results of classification accuracy between Bert and supervised learning techniques so I have to run your code in my dataset to get some results

**Comment by younesKha** [comment]
What is this file for '/content/adc.json'
and how can I get it

**Comment by younesKha** [comment]
and this file config.json

**Comment by younesKha** [comment]
I am using file code 
https://github.com/aub-mind/arabert/blob/master/araBERT_(Updated_Demo_TF).ipynb
Is the best implementation for araBert

**Comment by younesKha** [comment]
I found the above files, I hope I can run it

**Comment by WissamAntoun** [comment]
The easiest way is to run this notebook on google colab https://colab.research.google.com/ with a GPU runtime. And have the AraBERT model in your google drive. The config.json file is in the AraBERT model directory.
